api_category_directory:
    resource: 'category/'
    type: directory

api_post_directory:
    resource: 'post/'
    type: directory

index:
  path: /index
  controller: App\Controller\Index\IndexController
  methods:  [GET]

api_login_check:
    path: /login_check